### ISSUE TITLE
No enable button for Enchant Quality and Mend VPE zone autocasting

### ISSUE THREAD

**Issue by TurtlePlow** [Toby222/vpe-better-autocast#2]
Hi there, submitting a screenshot of the mod settings.

![image](https://github.com/Toby222/vpe-better-autocast/assets/171620908/c3937d32-a0b5-4a3e-90dd-e136ac189e95)

**Comment by Toby222** [comment]
Oop; GitHub didn't notify me of this ^^;
the "Cast while un-/drafted" toggles are what enable/disable the autocasting

**Comment by TurtlePlow** [comment]
Thank you for responding. Just to clarify my issue, I would like my pawn to auto cast enchant quality only in zones that have 'enchant' in the name, but they are casting enchant quality on everything with no discrimination. Now that I am reading the description for that option again, is that only for stockpile zones that are named, and not shelves?

**Comment by Toby222** [comment]
Ah yes. The name filter is only applied to stockpiles.
Off the top of my head, I'm not sure you can even name shelves/storage groups?
If you can, I'll try adding support for that later ^^;

**Comment by TurtlePlow** [comment]
It is not possible to name individual shelves, but it is possible to name storage groups though, like if you linked multiple shelves together. I'd appreciate it if you would be able to add it in the future but no rush. Currently, I am getting by perfectly okay with just having a stockpile for priority auto casting. :)

**Comment by Toby222** [comment]
It is actually possible to name individual shelves, which I just found out while testing
(It will create a storage group with a single member, which is neat!)
